version: '3.9'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_dockerventa
    environment:
      SA_PASSWORD: 'Your_password123!'
      ACCEPT_EULA: 'Y'
    ports:
      - "1433:1433"
    networks:
      - backend
    volumes:
      - sql_data:/var/opt/mssql

  dockerventa:
    build:
      context: .
    container_name: dockerventa
    ports:
      - "8002:8080"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=db;Database=VentaDB;User=sa;Password=Your_password123!;Encrypt=false;TrustServerCertificate=True;"
    networks:
      - backend

networks:
  backend:

volumes:
  sql_data:
